name: ds_postgres_database
description: PostgreSQL database provider for DartStream.
version: 0.0.1
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.10.9

resolution: workspace

dependencies:
  ds_database_base: ^0.0.2
  postgres: ^3.5.9

entry_point: "lib/ds_postgres_database_entry.dart"

