site:
  title: Dartstream OSS Docs
  start_page: dartstream::index.adoc
  url: https://docs.dartstreamoss.com/

content:
  sources:
    # 1) url: ..  ← use the parent folder (your repo root) as the Git repo
    # 2) branches: HEAD  ← match whatever branch you have checked out locally
    # 3) start_path  ← where inside the repo the component lives
    - url: ../..
      branches: HEAD
      start_path: dartstream/docs/components/dartstream


ui:
  bundle:
   # 1) Documentation Team Custom
   # 2) Antora Default
    url: ./ui/antora-ui-custom/ui-bundle
   # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  
