name: "AmazonAuth"
version: "1.0.0"
description: "Amazon authentication provider for Dartstream."
dependencies:
  - "Auth >=1.0.0"
entry_point: "lib/amazon_auth_provider.dart"

publish_to: none # Mark the package as non-publishable for local testing:

environment:
 sdk: ^3.7.0