name: ds_sentry_logging_provider
description: Sentry logging provider for DartStream.
version: "0.0.1"
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.10.9

resolution: workspace

dependencies:
  ds_logging_base: ^0.0.1
  sentry: ^9.9.2

entry_point: "lib/ds_sentry_logging_entry.dart"

