name: ds_logging_base
description: Base logging interfaces and manager for DartStream.
version: "0.0.1"
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.11.0

resolution: workspace

entry_point: "lib/ds_logging_base_export.dart"

