#This pubspec file imports is used for any dependencies for standard Dartstream features
name: ds_standard_features_grpc
description: Packages for our standard features grpc - maintained by the Dart team.
version: 0.0.1-pre+8
repository: https://github.com/dartstream

environment:
 sdk: ">=3.4.0 <4.0.0"

# Dependencies are added in sections alphabetically and according to features.
dependencies:

# STANDARD PACKAGES - Built By The Dart Team
  grpc: ^3.2.4
  matcher: ^0.12.16+1
 
#Globally Activated Package
#executables:
#   ds: ds_cli