name: ds_shelf_example
description: Example application demonstrating ds_shelf capabilities.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.9

dependencies:
  ds_shelf:
    path: ../
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  dotenv: ^4.2.0

dev_dependencies:
  ds_tools_testing: ^0.1.4
