name: ds_workspace
version: 0.0.1
description: A package for DartStream project-wide Melos configurations and scripts.
repository: https://github.com/dartstream

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  melos: ^5.3.0