#This pubspec file imports is used for any authentication framework features.
#This works for both mobile and web.
name: ds_middleware_base
description: Base package for DartStream authentication, including foundational classes and interfaces.
version: 0.0.1-pre+1
repository: https://github.com/aortem/dartstream

environment:
<<<<<<< HEAD:dartstream/dartstream_backend/packages/standard/standard_extensions/platform_services/middleware/base/pubspec.yaml
 sdk: ^3.8.1
=======
 sdk: ^3.8.1
>>>>>>> main:dartstream/dartstream_backend/packages/standard/extensions/middleware/base/pubspec.yaml

# Dependencies are added in sections alphabetically and according to features.
dependencies:


# STANDARD PACKAGES - Built By The Dart Team
