#This pubspec file is used for any dependencies that both the frontend and backend framework use(aka. shared dependencies)
name: ds_custom_middleware
description: DartStream Custom Middleware.  Use as the seoncdary option to Shelf Middleware.
version: 0.0.1-pre
repository: https://github.com/dartstream

environment:
 sdk: '>=3.0.0 <4.0.0'

# Dependencies are added in sections alphabetically and according to features.
dependencies:
  ds_standard_features: ^0.0.1-pre+5

# Dev dependencies are added in sections alphabetically and according to features.
dev_dependencies:
  ds_tools_testing: ^0.0.1-pre+1