#This pubspec file is used for any dependencies that both the frontend and backend framework use(aka. shared dependencies)
name: ds_custom_middleware
description: The root Yaml file.  Placeholder for future expansion.
version: 0.0.1-pre
# repository: https://github.com/my_org/my_repo

environment:
 sdk: '>=3.0.0 <4.0.0'

# Dependencies are added in sections alphabetically and according to features.
dependencies:
  ds_standard_features: ^0.0.1-pre+4
  web: ^0.5.1
  http: ^1.2.1

# Dev dependencies are added in sections alphabetically and according to features.
dev_dependencies:

#Cosmetic
  lints: ^3.0.0 #Included In ds_standard_features

  ds_tools_testing: ^0.0.1-pre