name: ds_google_mysql_database
description: MySQL database provider for DartStream using Google Cloud SQL.
version: 0.0.1
repository: https://github.com/aortem/dartstream
publish_to: none

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  mysql1: ^0.20.0
  ds_database_base:
    path: ../../../base
  ds_standard_features: ^0.0.7