name: ds_google_postgres_database
description: PostgreSQL database provider for DartStream using Google Cloud SQL.
version: 0.1.0
repository: https://github.com/aortem/dartstream
publish_to: none

environment:
  sdk: ^3.7.2

resolution: workspace

dependencies:
  postgres: ^3.5.5
  ds_database_base:
    path: ../../../base
  ds_standard_features: ^0.0.1-pre+11