name: ds_dartweb_framework_base
description: Core web framework package for DartStream.
version: 0.0.1-pre+1
publish_to: none
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.12.2

# Dependencies are added in sections alphabetically and according to features.
dependencies:
  # Standard packages maintained by Aortem.
  ds_standard_features: ^0.1.7
  flutter:
    sdk: flutter
  web: ^0.5.1
  ds_auth_base:
    path: ../../backend/packages/standard/standard_extensions/auth/base
  google_auth_provider:
    path: ../../backend/packages/standard/standard_extensions/auth/providers/google

dev_dependencies:
  flutter_lints: ^6.0.0
