name: ds_intellitoggle_provider_example
description: Example usage of the IntelliToggle feature flag provider for DartStream.
version: 0.0.1-pre+1
repository: https://github.com/aortem/dartstream
publish_to: none
environment:
  sdk: ^3.11.0

dependencies:
  ds_intellitoggle_provider: ^0.0.1
  ds_feature_flags_base: ^0.0.1
  ds_standard_features: ^0.1.6

dev_dependencies:
  ds_tools_testing: ^0.1.4