# STAGES OF OUR BUILD
stages:
  - build
  - test
  - deploy

# Allows manual deployment to qa environment for pre deploy testing purposes.
#include:
#  - local: tools/pipelines/woaccelerator-qa-ci.yml
#    rules:
#      - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "qa"
  # - local: deploys.yml
  #   rules:
  #     - if: $CI_COMMIT_BRANCH == "qa"

# Pre-Merge Environment #1 check build and delpoy Docker image using Cloud Build
dartstream-dev:pre_dev_deploy:
  image: google/cloud-sdk:alpine
  stage: deploy
  environment: dartstream-dev1
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" || $CI_COMMIT_REF_NAME == "development"
  before_script:
    - bash tools/gcloud_dev_acc.sh
  # when: manual
  script:
    - bash tools/pre_dev_deploy.sh

# Pre-Merge Environment #2 check build and deploy Docker image using Cloud Build
#dartstream-dev:pre_dev_deploy2:
#  image: google/cloud-sdk:alpine
#  stage: deploy
#  environment: dartstream-dev2
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" || $CI_COMMIT_REF_NAME == "development"
#  before_script:
#    - bash tools/gcloud_dev_acc.sh
#  when: manual
#  script:
#    - bash tools/pre_dev_deploy2.sh


# Build docker image using Cloud Build
dartstream-dev:build:
  image: google/cloud-sdk:alpine
  stage: build
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives" 
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_MERGE_REQUEST_APPROVED == "true" && $GITLAB_USER_LOGIN == "alphabetacreatives"
      changes:
        - dartstream-dev/*
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives" 
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_MERGE_REQUEST_APPROVED == "true" && $GITLAB_USER_LOGIN == "alphabetacreatives"
      changes:
        - docs/dartstream-dev/*
  before_script:
    - bash tools/gcloud_dev_acc.sh
 # when: manual
  script:
    - cd dartstream
    - tar -czf dartstream-dev.tgz *
    - gcloud builds submit dartstream-dev.tgz
      --tag us-central1-docker.pkg.dev/dartstream-dev/dartstream-dev/dartstream-dev:$CI_COMMIT_REF_SLUG
  retry: 2

# Deploy the container image to Cloud Run
dartstream-dev:dev_deploy:
  environment: dartstream-dev
  image: google/cloud-sdk:alpine
  stage: deploy
  rules:
   # - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" || $CI_COMMIT_REF_NAME == "development"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives" 
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_MERGE_REQUEST_APPROVED == "true" && $GITLAB_USER_LOGIN == "alphabetacreatives"
      changes:
        - dartstream-dev/*
   # - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" || $CI_COMMIT_REF_NAME == "development"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives" 
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_MERGE_REQUEST_APPROVED == "true" && $GITLAB_USER_LOGIN == "alphabetacreatives"
      changes:
        - docs/dartstream-dev/*
  needs: ["dartstream-dev:build"]
  before_script:
    - bash tools/gcloud_dev_acc.sh
  script:
    - gcloud run deploy dartstream-dev
      --image us-central1-docker.pkg.dev/dartstream-dev/dartstream-dev/dartstream-dev:$CI_COMMIT_REF_SLUG
      --region us-central1
      --service-account vcf-dev-cloud-cd@dartstream-dev.iam.gserviceaccount.com
  retry: 2