stages:
  - setup
  - unit_tests
  - integration_tests
  - e2e_tests

# Setup Stage
setup:
  stage: setup
  image: dart:stable
  tags:
    - dart
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
  script:
    - echo "Setting up environment..."
    - dart pub get
  artifacts:
    paths:
      - .dart_tool/
    expire_in: 1h
  retry: 2

# Unit Tests
unit_tests:
  stage: unit_tests
  image: dart:stable
  tags:
    - dart
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
  script:
    - echo "Running Unit Tests..."
    - dart test test/unit/ --reporter expanded
  artifacts:
    paths:
      - test-reports/unit/
    expire_in: 1d
  retry: 2

# Integration Tests
integration_tests:
  stage
