name: ds_lifecycle_base
description: Base lifecycle interfaces for DartStream reactive dataflow.
version: "0.0.1"
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.11.0

resolution: workspace
