#This pubspec file is used to import our standard features tooling.
name: ds_cli
description: Core Testing Components For Dartstream.
version: 0.0.1
repository: https://github.com/aortem/dartstream
publish_to: none

environment:
  sdk: ^3.8.1

# Dependencies are added in sections alphabetically and according to features.
dependencies:
  ds_discovery_provider:
    path: ../../standard/standard_extensions/platform_services/discovery
  ds_lifecycle_base:
    path: ../../standard/standard_extensions/reactive_dataflow/lifecycle/base
  ds_tools_testing: ^0.0.2

entry_point: "./bin/ds_cli.dart"
