#This pubspec file imports is used for any dependencies for standard DartStream features.

name: ds_vue_framework_base
description: Packages for our vue framework - maintained by Aortem.
version: 0.0.1-pre+1
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.12.2

# Dependencies are added in sections alphabetically and according to features.
dependencies:

# STANDARD PACKAGES - Maintained by Aortem
  ds_standard_features: ^0.1.7
