#This pubspec file is used for any dependencies that both the frontend and backend framework use(aka. shared dependencies)
name: ds_enhanced_features
description: Packages for our enhanced features
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
 sdk: ">=3.3.0 <4.0.0"

# Dependencies are added in sections alphabetically and according to features.
dependencies:

# MIDDLEWARE - USE ONLY ONE

# Shelf Middleware Import  // On By Default
#  ds_shelf: ^0.0.1

# Custom Middleware Import // Off By Default

# AUTHENTICATION SDK PACKAGES - USE ONLY ONE

# Amazon Cognito SDK
  amazon_cognito_identity_dart_2: ^3.6.2

# Core Custom Import

# Core Custom Import

#Cosmetic
  lints: ^2.1.0

#Testing Packages
  test: ^1.24.0
  mockito: ^5.0.0
  mocktail: ^1.0.3

#Globally Activated Package
executables:
   ds: ds_cli