name: ds_mongo_database
description: MongoDB database provider for DartStream.
version: 0.0.1
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  ds_database_base: ^0.0.2
  mongo_dart: ^0.10.6

entry_point: "lib/ds_mongo_database_entry.dart"

