name: ds_custom_middleware
description: DartStream Custom Middleware.  Use as the secondary option to Shelf Middleware.
version: 0.0.1-pre
repository: https://github.com/aortem/dartstream

environment:
 sdk: ^3.7.2