#This pubspec file is used for any dependencies that both the frontend and backend framework use(aka. shared dependencies)
name: _
description: Core Testing Components Within Larger DartStream Ecosystem.
version: 0.0.1
repository: https://github.com/aortem/dartstream
publish_to: none

environment:
 sdk: ^3.7.2

# Dependencies are added in sections alphabetically and according to features.
dependencies:
  ds_tools_testing: ^0.0.2
