#This pubspec file imports is used for any dependencies that both the frontend and backend framework use(aka. shared dependencies)
name: ds_standard_features
description: Packages for our standard features - maintained by the Dart team.
version: 0.0.1-pre
# repository: https://github.com/my_org/my_repo

environment:
 sdk: ">=3.3.0 <4.0.0"

# Dependencies are added in sections alphabetically and according to features.
dependencies:

# MIDDLEWARE - USE ONLY ONE

# Shelf Middleware Import  // On By Default
  ds_shelf: ^0.0.1-pre

# Custom Middleware Import // Off By Default


# STANDARD PACKAGES - Built By The Dart Team

  args: ^2.4.2
  async: ^2.11.0
  build: ^2.4.1
  characters: ^1.3.0
  collection: ^1.18.0
  convert: ^3.1.1
  crypto: ^3.0.3
  fake_async: ^1.3.1
  ffi: ^2.1.2
  fixnum: ^1.1.0
  grpc: ^3.2.4
  http: ^1.2.1
  http2: ^2.3.0
  http_parser: ^4.0.2
  intl: ^0.18.0
  intl_translation: ^0.18.1
  logging: ^1.2.0
  matcher: ^0.12.16+1
  meta: ^1.14.0
  os_detect: ^2.0.1
  path: ^1.9.0
  typed_data: ^1.3.2
  web: ^0.5.1
 

## PACKAGES BELOW ARE STANDARDIZED ACROSS ALL YAML FILES

#Cosmetic
  lints: ^2.1.0

#Testing Packages
  test: ^1.24.0
  mockito: ^5.4.4
  mocktail: ^1.0.3

#Globally Activated Package
#executables:
#   ds: ds_cli