name: Documentation
description: Improve Documentation
title: "[Documentation]: "
labels: ["community::documentation"]
#projects: ["octo-org/1", "octo-org/44"]
assignees:
  - ABC2015
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: user-question
    attributes:
      label: What is missing in the documentation?
      description: Also tell us, what are you expecting in the documentaion?
      placeholder: Tell us what you see!
      value: "Missing Context!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - "latest"
        - "pre-release"
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What system do you see the problem on?
      multiple: true
      options:
        - Flutter Web
        - Flutter Mobile
        - Flutter Desktop
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true