name: ds_eventarc_events_provider
description: " Use Eventarc (with Pub/Sub) for a durable, schema-driven event bus."
version: "0.0.1-pre"
repository: https://github.com/aortem/dartstream

publish_to: none # Mark the package as non-publishable for local testing:

environment:
 sdk: ^3.8.1

resolution: workspace

entry_point: "lib/amazon_auth_provider.dart"