#This pubspec file is used for any dependencies that both the frontend and backend framework use(aka. shared dependencies)
name: ds_cli
description: Main Dartstream CLI.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
 sdk: ">=3.3.0 <4.0.0"

# Dependencies are added in sections alphabetically and according to features.
dependencies:

# Shelf Middleware
  ds_shelf: ^0.0.1-pre

# Custom Middleware
#  TBD: ^0.0.1

# Standard DartStream Features
  ds_standard_features: ^0.0.1-pre

# Dev dependencies are added in sections alphabetically and according to features.
dev_dependencies:

#CLI
  cli_util: ^0.4.1

#Cosmetic
  lints: ^3.0.0 #Included In ds_standard_features

#Testing Packages
  test: ^1.24.0
  mockito: ^5.0.0
  mocktail: ^1.0.3



#Globally Activated Package
executables:
   ds: ds_cli