name: ds_cognito_auth_provider
description: "Amazon authentication provider for Dartstream."
version: "0.0.1"
repository: https://github.com/aortem/dartstream

resolution: workspace


environment:
  sdk: ^3.10.9

resolution: workspace

entry_point: "lib/amazon_auth_provider.dart"
