name: ds_cognito_auth_provider
description: "Amazon authentication provider for Dartstream."
version: "0.0.1-pre+1"
repository: https://github.com/aortem/dartstream

publish_to: none # Mark the package as non-publishable for local testing:

environment:
 sdk: ^3.10.7

dependencies:
  ds_auth_base:
    path: ../../../base
  amazon_cognito_identity_dart_2: ^3.0.0

resolution: workspace

entry_point: "lib/ds_cognito_auth_provider.dart"
