name: stytch_auth_example
description: Stytch Authentication example for DartStream
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.12.2

dependencies:
  # HTTP Server
  shelf: ^1.4.2

dev_dependencies:
  lints: ^6.1.0
