#This pubspec file is used for any dependencies that both the frontend and backend framework use(aka. shared dependencies)
name: ds_shelf
description: Core Shelf Components Within Larger DartStream Ecosystem.
version: 0.0.1-pre+5
repository: https://github.com/aortem/dartstream

environment:
 sdk: ^3.8.1

#resolution: workspace

# Dependencies are added in sections alphabetically and according to features.
dependencies:

#------------------MIDDLEWARE - Packages Built By The Dart Team -----------------
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_packages_handler: ^3.0.2
  shelf_proxy: ^1.0.4
  shelf_static: ^1.1.3
  shelf_web_socket: ^3.0.0
  shelf_test_handler: ^2.0.2

  # Note: shelf_router_generator and shelf_packages_handler are not direct dependencies
  # They might be part of your dev_dependencies for code generation or testing.

# Dev dependencies are added in sections alphabetically and according to features.
dev_dependencies:


