name: ds_shelf
description: DartStream Shelf Middleware.  Use as the secondary option to Shelf Middleware.
version: 0.0.1-pre+5
repository: https://github.com/aortem/dartstream

environment:
 sdk: ^3.8.1

# Dependencies are added in sections alphabetically and according to features.
dependencies:

# Shelf Dependencies - Mainatined by the Dart Team 
  shelf: ^1.4.1
  shelf_router: ^1.0.0
  shelf_proxy: ^1.0.0
  shelf_static: ^1.0.0
  shelf_web_socket: ^1.0.0
  shelf_packages_handler: ^3.0.2
  shelf_test_handler: ^2.0.2
  http_multi_server: ^3.2.1
  web_socket_channel: ^2.1.0

# Standard Dependencies - Mainatined by the Aortem Team 
  ds_standard_features: ^0.0.1-pre+11
  ds_tools_testing: ^0.0.1-pre+2
  ds_tools_general: ^0.0.1-pre


#  OPTION 2
 ds_shelf_cors: ^0.0.1-pre

# Dev dependencies are added in sections alphabetically and according to features.
dev_dependencies: