name: ds_storage_base
description: Base storage interfaces and manager for DartStream.
version: "0.0.1"
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.10.9

resolution: workspace

entry_point: "lib/ds_storage_base_export.dart"

