name: ds_storage_gcp
description: Google Cloud Storage provider for DartStream.
version: "0.0.1"
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.10.8

resolution: workspace

dependencies:
  ds_storage_base: ^0.0.1
  googleapis: ^13.2.0
  googleapis_auth: ^2.0.0

entry_point: "lib/ds_storage_gcp_entry.dart"
