name: magic_example_server
description: A simple backend server demonstrating Magic Auth usage.
version: 1.0.0
environment:
  sdk: ^3.10.9

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  ds_auth_base: any
  ds_magic_auth_provider: any

dependency_overrides:
  ds_auth_base:
    path: ../../../base
  ds_magic_auth_provider:
    path: ../
