name: ds_okta_auth_provider
description: Fingerprint authentication provider for Dartstream.
version: 0.0.1-pre
repository: https://github.com/aortem/dartstream

publish_to: none # Mark the package as non-publishable for local testing:

environment:
 sdk: ^3.9.0

resolution: workspace

dependencies:
  okta_identity_dart_auth_sdk: ^0.0.1-pre
  ds_auth_base: ^0.0.1
  ds_standard_features: ^0.0.8