name: ds_fingerprint_auth_provider
description: Fingerprint authentication provider for DartStream.
version: 0.0.1
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  fingerprint_dart_auth_sdk: ^0.0.3
  ds_auth_base: ^0.0.2
  ds_standard_features: ^0.1.6

dev_dependencies:
  ds_tools_testing: ^0.1.4
