name: ds_message_broker_base
description: Base interfaces and manager for DartStream message brokers.
version: "0.0.1"
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.11.0

resolution: workspace

entry_point: "lib/ds_message_broker_base_export.dart"

