name: ds_auth_base
description: Base package for DartStream authentication, including foundational classes and interfaces.
version: 0.0.1-pre
repository: https://github.com/aortem/dartstream

environment:
 sdk: ^3.8.1 

resolution: workspace

# Dependencies are added in sections alphabetically and according to features.
dependencies:
  firebase_dart_admin_auth_sdk: ^0.0.2

#  Add or remove the supported Auth SDK providers as needed (ie. firebase_dart_admin_auth_sdk: ^latest)

