name: ds_auth_base
description: Base package for DartStream authentication, including foundational classes and interfaces.
version: 0.0.1-pre+1
repository: https://github.com/aortem/dartstream

environment:
 sdk: ^3.8.1 

# Dependencies are added in sections alphabetically and according to features.
dependencies:

  firebase_dart_admin_auth_sdk: ^0.0.1

# STANDARD PACKAGES - Built By The Dart Team
