name: ds_transmit_auth_provider
description: Transmit Authentication Provider For Dartstream.
version: 0.0.2
repository: https://github.com/aortem/dartstream

environment:
 sdk: ^3.8.2

resolution: workspace

dependencies:
  transmit_dart_auth_sdk: ^0.0.2
  ds_auth_base: ^0.0.1
  ds_standard_features: ^0.0.8