import 'dart:convert';

/// Generated by Dartstream CLI (`generate --type client`).
/// Source spec version: 3.0.0
class DSDemoClient {
  DSDemoClient({
    required DSClientTransport transport,
    String? baseUrl,
  })  : _transport = transport,
        _baseUrl = (baseUrl ?? _defaultBaseUrl).trim();

  static const String _defaultBaseUrl = 'https://api.example.com';
  final DSClientTransport _transport;
  final String _baseUrl;

  String get baseUrl => _baseUrl;

  /// Health check
  Future<DSClientResponse> getHealth({
    Map<String, String> headers = const {},
    Map<String, dynamic>? query,
    Object? body,
  }) {
    return _transport.send(
      method: 'GET',
      path: _renderPath('/health'),
      headers: headers,
      query: query,
      body: body,
    );
  }


  String _renderPath(String path) {
    if (_baseUrl.isEmpty) {
      return path;
    }
    final normalizedBase = _baseUrl.endsWith('/')
        ? _baseUrl.substring(0, _baseUrl.length - 1)
        : _baseUrl;
    final normalizedPath = path.startsWith('/') ? path : '/$path';
    return '$normalizedBase$normalizedPath';
  }
}

class DSClientResponse {
  DSClientResponse({
    required this.statusCode,
    required this.body,
    this.headers = const {},
  });

  final int statusCode;
  final String body;
  final Map<String, String> headers;

  dynamic jsonOrNull() {
    if (body.trim().isEmpty) {
      return null;
    }
    return jsonDecode(body);
  }
}

abstract class DSClientTransport {
  Future<DSClientResponse> send({
    required String method,
    required String path,
    Map<String, String> headers,
    Map<String, dynamic>? query,
    Object? body,
  });
}

class DSMemoryTransport implements DSClientTransport {
  DSMemoryTransport({
    this.defaultStatusCode = 200,
    this.defaultBody = '{"ok":true}',
  });

  final int defaultStatusCode;
  final String defaultBody;
  final List<DSRequestLog> requests = <DSRequestLog>[];

  @override
  Future<DSClientResponse> send({
    required String method,
    required String path,
    Map<String, String> headers = const {},
    Map<String, dynamic>? query,
    Object? body,
  }) async {
    requests.add(
      DSRequestLog(
        method: method,
        path: path,
        headers: headers,
        query: query,
        body: body,
      ),
    );

    return DSClientResponse(
      statusCode: defaultStatusCode,
      body: defaultBody,
      headers: const {'content-type': 'application/json'},
    );
  }
}

class DSRequestLog {
  DSRequestLog({
    required this.method,
    required this.path,
    required this.headers,
    this.query,
    this.body,
  });

  final String method;
  final String path;
  final Map<String, String> headers;
  final Map<String, dynamic>? query;
  final Object? body;
}
