name: ds_auth0_auth_provider
description: Auth0 authentication provider for Dartstream.
version: 0.0.1-pre
repository: https://github.com/aortem/dartstream

environment:
 sdk: ^3.8.1

resolution: workspace

dependencies:
  firebase_dart_admin_auth_sdk: ^0.0.2
  ds_auth_base: ^0.0.1-pre
  ds_standard_features: ^0.0.4