name: ds_stytch_auth_provider
description: Stytch authentication provider for Dartstream.
version: 0.0.3
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.10.9

resolution: workspace

dependencies:
  ds_auth_base: ^0.0.2
  ds_standard_features: ^0.1.6

dev_dependencies:
  test: ^1.25.0
