name: ds_sql_database
description: SQL database providers for DartStream, including PostgreSQL and MySQL implementations.
version: 0.1.0
repository: https://github.com/aortem/dartstream
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  postgres: ^3.5.5
  mysql1: ^0.20.0
  ds_database_base:
    path: ../../base
  ds_standard_features: ^0.0.1-pre+11
