name: ds_dartstream
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
 sdk: "^3.3.0"

# Dependencies are added in sections aplhabetically and according to features.
dependencies:



  postgres: ^3.0.0 # For PostgreSQL
  aws_signature_v4: ^0.5.0 # For AWS DynamoDB
  http: ^1.1.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  path: ^1.9.0
  mime: ^1.0.5

  # path: ^1.8.0

# Dev dependencies are added in sections aplhabetically and according to features.
dev_dependencies:

#CLI
  dcli: ^3.4.0

#TBD
  lints: ^2.1.0
  test: ^1.24.0
