name: ds_magic_auth_provider
description: DartStream package for Magic authentication provider.
version: 0.0.2
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  magic_dart_auth_sdk: ^0.0.3
  ds_auth_base: ^0.0.2
  ds_standard_features: ^0.1.6

dev_dependencies:
  ds_tools_testing: ^0.1.4
