name: ds_magic_auth_provider
description: DartStream package for Magic authentication provider.
version: 0.0.1
repository: https://github.com/aortem/dartstream

environment:
 sdk: ^3.10.7

resolution: workspace

dependencies:
  magic_dart_auth_sdk: ^0.0.3
  ds_auth_base: ^0.0.1
  ds_standard_features: ^0.1.5