name: ds_concurrency
description: Dartstream Concurrency Extension for multi-threading and isolate management.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.11.0

dependencies:
  # The standard engine package name is ds_dartstream_standard_engine
  ds_dartstream_standard_engine:
    path: ../../standard_engine

dev_dependencies:
  ds_tools_testing: ^0.1.4
