name: ds_entraid_auth_provider
description: Azure authentication provider for Dartstream.
version: 0.0.1-pre
repository: https://github.com/aortem/dartstream

publish_to: none # Mark the package as non-publishable for local testing:

environment:
 sdk: ^3.8.1
 