name: ds_aws_storage_provider
description: S3-compatible storage provider for DartStream.
version: "0.0.1"
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  ds_storage_base: ^0.0.1
  minio: ^3.5.8

entry_point: "lib/ds_storage_aws_entry.dart"

