name: ds_transmit_auth_provider
description: Transmit authentication provider for DartStream.
version: 0.0.4
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  transmit_dart_auth_sdk: ^0.0.5
  ds_auth_base: ^0.0.2
  ds_standard_features: ^0.1.7

dev_dependencies:
  ds_tools_testing: ^0.1.4
