# The DartStream Code Engine
name: ds_dartstream_standard_engine
description: The core standard engine for DartStream applications.
version: 0.0.1
homepage: https://dartstream.io
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.11.0

resolution: workspace

# Dependencies are added in sections alphabetically and according to features.
dependencies:
# Packages needed for the app to run
  ds_lifecycle_base: ^0.0.1
  ds_standard_features: ^0.1.6

dev_dependencies:
# Packages only needed for development/testing
  ds_tools_testing: ^0.1.4
