stages:
  - publish_package

# Publish Package
publish_package:
  image: google/cloud-sdk:alpine
  stage: publish_package
  environment:
    name: production
  before_script:
    - bash tools/scripts/gcloud_prod_acc_cloudbuild.sh
    - apk add --no-cache wget unzip
  # Download Dart SDK using wget with -O flag
    - wget -q -O dart-sdk.zip https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dart-sdk-linux-x64-release.zip
  # Check if the file was downloaded successfully
    - |
      if [ ! -f dart-sdk.zip ]; then
        echo "Dart SDK download failed."
        exit 1
      fi
  script:
    - gcloud auth print-identity-token --audiences=https://pub.dev | dart pub token add https://pub.dev
    - dart pub publish --dry-run
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
    - if: '$CI_COMMIT_REF_NAME == "development"'
      when: always