stages:
  - publish_package

# Publish Package
publish_package:
  image: google/cloud-sdk:alpine
  stage: publish_package
  environment:
    name: production
  before_script:
    - bash tools/scripts/gcloud_prod_acc_cloudbuild.sh
     # Install dependencies for Dart on Alpine
    - apk add --no-cache wget unzip
    # Download and install Dart SDK (adjust version as needed)
    - wget -qO- https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dart-sdk-linux-x64-release.zip > dart-sdk.zip
    - unzip dart-sdk.zip -d /usr/lib
    - export PATH="/usr/lib/dart-sdk/bin:$PATH"
  script:
    - gcloud auth print-identity-token --audiences=https://pub.dev | dart pub token add https://pub.dev
    - dart pub publish --dry-run
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
    - if: '$CI_COMMIT_REF_NAME == "development"'
      when: always