#This pubspec file is used for any dependencies that both the frontend and backend framework use(aka. shared dependencies)
name: ds_tools_linting
description: Core Linting Components Within Larger DartStream Ecosystem.
version: 0.0.1-pre+1
# repository: https://github.com/my_org/my_repo

environment:
 sdk: ">=3.3.0 <4.0.0"

# Dependencies are added in sections alphabetically and according to features.
dependencies:

#Testing Packages
  flutter_lints: ^3.0.2
  lints: ^3.0.0
  very_good_analysis: ^5.1.0


#Globally Activated Package
#executables:
#   ds: ds_cli