#This pubspec file imports is used for any authentication framework features.
#This works for both mobile and web.
name: ds_middleware_base
description: Base middleware interfaces and contracts for DartStream.
version: 0.0.2-pre+1
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.12.2

resolution: workspace

# Dependencies are added in sections alphabetically and according to features.
dependencies:


# STANDARD PACKAGES - Maintained by Aortem
