#This pubspec file is used for the Main Dartstream CLI
#It pulls in both DS Shelf and DS Custom Middlewrae packages for the user to scaffold with.

name: ds_cli
description: Main Dartstream CLI.
version: 0.0.1-pre+1
repository: https://github.com/aortem/dartstream

environment:
 sdk: ^3.8.1

# Dependencies are added in sections alphabetically and according to features.
dependencies:

# DS Shelf Middleware
  ds_shelf: ^0.0.1-pre
  ds_custom_middleware: ^0.0.1-pre

# DS Custom Middleware
#  TBD: ^0.0.1

# DS Standard Features
  ds_standard_features: ^0.0.1-pre+5

# DS Tools Testing
  ds_tools_testing: ^0.0.1-pre

#DS Tools CLI
  ds_tools_cli: ^0.0.1-pre+2

# Dev dependencies are added in sections alphabetically and according to features.
dev_dependencies:

#Cosmetic
  lints: ^4.0.0 #Included In ds_standard_features

#Globally Activated Package
executables:
   ds: ds_cli