<template>
  <transition name="fade">
    <div
      v-if="isOpen"
      class="fixed inset-0 bg-black bg-opacity-40 z-50 flex justify-end"
    >
      <div
        class="bg-white w-full sm:w-[500px] max-h-screen my-auto sm:my-4 mr-3 rounded-2xl shadow-xl overflow-y-auto relative"
      >
        <div
          class="flex items-center justify-between p-4 border-b bg-[#F3F5F7]"
        >
          {{ mode === "edit" ? "Edit Flag" : "Add New Flag" }}
          <button
            type="button"
            @click.stop.prevent="close"
            class="text-gray-500 hover:text-gray-700"
          >
            ✕
          </button>
        </div>
        <form class="space-y-6" @submit.prevent="onSubmit">
          <div class="p-4 m-4 space-y-4 border border-gray rounded-[16px]">
            <div class="flex gap-3">
              <div
                class="flex items-center space-x-2 h-9 w-9 px-2 py-2 bg-[#E5E5E5] rounded-full"
              >
                <img src="/assets/images/flag.png" alt="" class="w-auto" />
              </div>
              <div class="">
                <label class="block font-medium text-black">Flag Details</label>
                <p class="text-xs text-gray-500">Enter Flags Details</p>
              </div>
            </div>
            <div class="">
              <img src="/assets/images/divider.png" alt="" class="w-auto" />
            </div>
            <div class="space-y-4">
              <div class="flex gap-4">
                <div class="w-1/2">
                  <label class="block font-medium"
                    >Name
                    <span class="text-[#0062FF] font-medium">*</span></label
                  >
                  <!-- data attribute is for cypress test -->
                  <input
                    v-model="form.name"
                    class="w-full border rounded-[8px] px-2 py-2 text-gray-900"
                    type="text"
                    name="name"
                    data-cy="input-flag-name"
                  />
                </div>

                <div class="w-1/2">
                  <label class="flex font-medium"
                    >Key
                    <span class="text-[#0062FF]"> (autogenerated)</span></label
                  >
                  <div class="relative w-full">
                    <input
                      v-model="form.key"
                      class="w-full border rounded-[8px] px-3 py-2 text-gray-900 pr-8"
                      type="text"
                      name="key"
                      disabled
                    />
                    <img
                      src="/assets/images/copy.png"
                      alt="Copy"
                      class="absolute right-3 top-1/2 -translate-y-1/2 h-4 cursor-pointer"
                      @click="copyKey"
                    />
                  </div>
                </div>
              </div>

              <div>
                <label class="block font-medium"
                  >Description
                  <span class="text-red-500 font-medium">*</span></label
                >
                <!-- data attribute is for cypress test -->

                <textarea
                  v-model="form.description"
                  name="description"
                  data-cy="input-flag-description"
                  class="w-full border rounded-[8px] px-3 py-2"
                  placeholder="Message..."
                  maxlength="200"
                ></textarea>
              </div>

              <!-- <div>
                <label class="block font-medium mb-1">Environment Visibility (where it's active)</label>


                <div class="flex flex-wrap gap-2 mb-2">
                  <span v-for="(tag, index) in tags" :key="index"
                    class="bg-blue-100 text-blue-800 px-3 py-1 rounded-full flex items-center space-x-2">
                    <span>{{ tag }}</span>
                    <button class="ml-1 text-blue-500 hover:text-red-500" @click="removeTag(index)">
                      ✕
                    </button>
                  </span>
                </div>


                <input v-model="tagInput" @keydown.enter.prevent="addTag" placeholder="Type and press Enter to add"
                  class="w-full border rounded-[8px] px-3 py-2" />
              </div> -->
              <div>
                <label class="block font-medium"
                  >Environment visibility
                  <span class="text-[#0062FF] font-medium"
                    >(where it’s active)</span
                  ></label
                >
                <!-- data attribute is for cypress test -->

                <select
                  data-cy="environment-select"
                  class="w-full border rounded-[8px] px-3 py-2"
                  v-model="form.environment"
                  required
                >
                  <option value="">Select</option>
                  <option value="production">Production</option>
                  <!-- <option value="staging">Staging</option>
                  <option value="development">Development</option> -->
                </select>
              </div>
              <div>
                <label class="block font-medium"
                  >Flag Type
                  <span class="text-[#0062FF] font-medium">*</span></label
                >
                <select
                  data-cy="flag-select"
                  class="w-full border rounded-[8px] px-3 py-2"
                  v-model="form.type"
                  required
                >
                  <option value="">Select</option>
                  <option value="boolean">Boolean</option>
                  <option value="string">String</option>
                  <option value="number">Number</option>
                  <option value="json">JSON</option>
                </select>
              </div>
            </div>
          </div>
          <div
            class="flex items-center justify-between bg-[#D8EABC] p-2 m-4 rounded-[8px]"
          >
            <div class="flex gap-3">
              <img src="/assets/images/exchange.png" alt="" class="w-6" />
              Make this flag "on" default
            </div>

            <!-- Switch Wrapper -->
            <label class="inline-flex items-center cursor-pointer">
              <!-- Hidden input for accessibility and state tracking -->
              <input
                type="checkbox"
                v-model="form.defaultValue"
                class="sr-only"
              />

              <!-- Track -->
              <div
                class="w-10 h-5 rounded-full transition-colors duration-300 relative"
                :class="form.defaultValue ? 'bg-[#7AA734]' : 'bg-gray-300'"
              >
                <div
                  class="absolute top-0 left-0 w-5 h-5 bg-white rounded-full shadow-md transform transition-transform duration-300"
                  :class="form.defaultValue ? 'translate-x-5' : 'translate-x-0'"
                ></div>
              </div>
            </label>
          </div>
          <div class="p-4 m-4 space-y-4 border border-gray rounded-[16px]">
            <div class="flex gap-3">
              <div
                class="flex items-center space-x-2 h-9 w-9 px-2 py-2 bg-[#E5E5E5] rounded-full"
              >
                <img src="/assets/images/envir.png" alt="" class="w-auto" />
              </div>
              <div class="">
                <h3 class="text-md">Flag Variations</h3>
                <p class="text-xs text-gray-500">
                  manage your variations for your flag
                </p>
              </div>
            </div>

            <!-- Dynamic Rows -->
            <div
              v-for="(variation, index) in form.flag_variations"
              :key="index"
              class="flex gap-4 items-end mb-4"
            >
              <!-- Variation Name -->
              <div class="w-1/2">
                <label class="block font-medium text-black">
                  Variation Name
                  <span class="font-medium text-[#0062FF]">*</span>
                </label>
                <input
                  v-model="variation.name"
                  data-cy="input-variation-name"
                  class="w-full border rounded-[8px] px-2 py-2 text-gray-800"
                  type="text"
                  :name="`variationName_${index}`"
                />
              </div>

              <!-- Variation Value -->
              <div
              class="w-1/2">
                <label class="block font-medium text-black">
                  Variation Value
                  <span class="font-medium text-[#0062FF]">*</span>
                </label>

                <!-- Boolean: dropdown -->
                <select
                  data-cy="input-variation-value" 
                  v-if="form.type === 'boolean'"
                  v-model="variation.value"
                  class="w-full border rounded-[8px] px-2 py-2 text-gray-800"
                  :name="`variationValue_${index}`"
                >
                  <option :value="true">true</option>
                  <option :value="false">false</option>
                </select>

                <!-- String: simple text input -->
                <input
                  data-cy="input-variation-value" 
                  v-else-if="form.type === 'string'"
                  v-model="variation.value"
                  class="w-full border rounded-[8px] px-2 py-2 text-gray-800"
                  type="text"
                  :name="`variationValue_${index}`"
                />

                <!-- JSON: textarea with validation on blur -->
                <div v-else-if="form.type === 'json'">
                  <textarea
                    data-cy="input-variation-value"
                    v-model="variation.rawJson"
                    class="w-full border rounded-[8px] px-2 py-2 text-gray-800"
                    rows="4"
                    :name="`variationValue_${index}`"
                    placeholder='{"key":"value"}'
                  ></textarea>
                  <p
                    v-if="variation._jsonError"
                    class="text-red-600 text-sm mt-1"
                  >
                    {{ variation._jsonError }}
                  </p>
                </div>

                <!-- Number: numeric input (casts to Number) -->
                <input
                  v-else-if="form.type === 'number'"
                  data-cy="input-variation-value"
                  v-model.number="variation.value"
                  class="w-full border rounded-[8px] px-2 py-2 text-gray-800"
                  type="number"
                  step="any"
                  inputmode="decimal"
                  :name="`variationValue_${index}`"
                />

                <!-- Fallback (if type is unknown) -->
                <input
                  v-else
                  v-model="variation.value"
                  data-cy="input-variation-value"
                  class="w-full border rounded-[8px] px-2 py-2 text-gray-800"
                  type="text"
                  :name="`variationValue_${index}`"
                />
              </div>

              <!-- Trash Icon -->
              <div class="flex items-end pb-2">
                <button
                  type="button"
                  @click="removeVariation(index)"
                  class="hover:opacity-80 p-2"
                >
                  <svg
                    class="w-8 h-8"
                    viewBox="0 0 20 40"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M16.25 14.584L15.7336 22.9382C15.6016 25.0727 15.5356 26.1399 15.0006 26.9072C14.7361 27.2866 14.3955 27.6067 14.0006 27.8473C13.2018 28.334 12.1325 28.334 9.99395 28.334C7.8526 28.334 6.78192 28.334 5.98254 27.8464C5.58733 27.6054 5.24666 27.2847 4.98224 26.9047C4.4474 26.1361 4.38288 25.0674 4.25384 22.9299L3.75 14.584"
                      stroke="#FB4848"
                      stroke-width="1.5"
                      stroke-linecap="round"
                    />
                    <path
                      d="M2.5 14.5837H17.5M13.3798 14.5837L12.8109 13.4101C12.433 12.6305 12.244 12.2408 11.9181 11.9977C11.8458 11.9437 11.7692 11.8958 11.6892 11.8542C11.3283 11.667 10.8951 11.667 10.0288 11.667C9.14069 11.667 8.69665 11.667 8.32974 11.8621C8.24842 11.9053 8.17082 11.9552 8.09774 12.0113C7.76803 12.2642 7.58386 12.6683 7.2155 13.4764L6.71077 14.5837"
                      stroke="#FB4848"
                      stroke-width="1.5"
                      stroke-linecap="round"
                    />
                    <path
                      d="M7.9165 23.75L7.9165 18.75"
                      stroke="#FB4848"
                      stroke-width="1.5"
                      stroke-linecap="round"
                    />
                    <path
                      d="M12.0835 23.75L12.0835 18.75"
                      stroke="#FB4848"
                      stroke-width="1.5"
                      stroke-linecap="round"
                    />
                  </svg>
                </button>
              </div>
            </div>

            <!-- Add More Button -->
            <div class="w-full">
              <button
                @click="addVariation"
                type="button"
                class="px-4 py-2 w-full flex gap-3 justify-center rounded text-black bg-[#F5F7FA]"
              >
                <img
                  src="/assets/images/grayadd.png"
                  alt=""
                  class="w-6"
                  :class="isOn ? '' : 'opacity-50'"
                />
                Add More Variations
              </button>
            </div>
            <div class="p-4">
              <div class="flex justify-between gap-2 border-t pt-4">
                <button
                  type="button"
                  @click="close"
                  class="px-4 py-2 bg-[#F5F7FA] w-full rounded-[8px]"
                >
                  Cancel
                </button>
                <button
                  data-cy="button-submit-flag"
                  class="px-4 py-2 bg-[#42489E] text-white w-full rounded-[8px]"
                >
                  {{ mode === "edit" ? "Update Flag" : "Create Flag" }}
                </button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </transition>
</template>

<script setup>
import { watch } from "vue";
import { useToast } from "vue-toastification";
const { $api } = useNuxtApp();
const props = defineProps(["isOpen", "mode", "flag"]);
const emit = defineEmits(["close", "submitted", "error","refreshFlags"]);
const close = () => {
  emit("close");
};
const { selectedProjectId, setSelectedProject } = useSelectedProject();
const toast = useToast();
const initialForm = {
  name: "",
  key: "",
  description: "",
  defaultValue: false,
  environment: "",
  type: "",
  flag_variations: [{ name: "", value: "" }],
};

const form = ref({ ...initialForm });

// Add a new variation row
function addVariation() {
  form.value.flag_variations.push({ name: "", value: "" });
}

// Remove a variation row by index
function removeVariation(index) {
  form.value.flag_variations.splice(index, 1);
}
const onSubmit = async () => {
  try {
    let res;

    if (props.mode === "edit") {
      res = await $api(
        `/api/flags/projects/${selectedProjectId.value}/flags/${form.value.key}`,
        {
          method: "PATCH",
          body: { ...form.value },
        }
      );
    } else {
      res = await $api(
        `/api/flags/projects/${selectedProjectId.value}/flags`,
        {
          method: "POST",
          body: { ...form.value },
        }
      );
    }

    if (res) {
      if (props.mode !== "edit") {
        form.value = {
          ...initialForm,
          flag_variations: [{ name: "", value: "" }],
        };
      }

      emit("refreshFlags");
      emit(
        res.success ? "submitted" : "error",
        res.message ||
          (props.mode === "edit"
            ? "Flag updated successfully!"
            : "Flag created successfully!")
      );
    }
  } catch (error) {
    console.error("Flag error:", error.data || error.message);
    emit(
      "error",
      (error.data || error.message) ||
        (props.mode === "edit"
          ? "Update Flag failed. Please try again."
          : "Create Flag failed. Please try again.")
    );
  }
};


// Watch name and update key
watch(
  () => props.flag,
  (newFlag) => {
    if (props.mode === "edit" && newFlag) {
      form.value = {
        name: newFlag.name || "",
        key: newFlag.key || "",
        description: newFlag.description || "",
        defaultValue: newFlag.defaultValue ?? false,
        environment: newFlag.environment || "",
        type: newFlag.type || "",
        flag_variations: newFlag.flag_variations?.length
          ? [...newFlag.flag_variations]
          : [{ name: "", value: "" }],
      };
    }
  },
  { immediate: true } // run right away if flag already exists
);

// Watch name and update key for form
watch(
  () => form.value.name,
  (newName) => {
    if(props.mode !== "edit" && newName){    
    form.value.key = newName
      .toLowerCase()
      .trim()
      .replace(/\s+/g, "-") // spaces → dashes
      .replace(/[^a-z0-9\-]/g, ""); // remove invalid chars
    }
  }
);

const copyKey = () => {
  navigator.clipboard
    .writeText(form.value.key)
    .then(() => {
      toast.success("Copied to clipboard");
    })
    .catch((err) => {
      console.error("Copy failed ❌", err);
    });
};
</script>
