name: ds_middleware
description: DartStream Middleware.  Use as the secondary option to Shelf Middleware.
version: 0.0.1-pre
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.10.9

resolution: workspace

dependencies:
  ds_standard_features: ^0.1.6
  ds_tools_testing: ^0.1.4
  mime: ^1.0.0

dev_dependencies:
  test: ^1.24.0
