name: ds_middleware
description: DartStream Middleware.  Use as the secondary option to Shelf Middleware.
version: 0.0.1-pre
publish_to: none
repository: https://github.com/aortem/dartstream


environment:
  sdk: ^3.12.2
resolution: workspace
dependencies:
  ds_standard_features: ^0.1.7
  ds_shelf:
    path: ../ds_shelf
  mime: ^1.0.0

  path: any
  logging: any
  # Streaming
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
dev_dependencies:
  test: ^1.24.0
  mockito: ^5.0.0
  mocktail: ^1.0.3
  shelf: ^1.4.0
