name: ds_intellitoggle_provider
description: IntelliToggle feature flag provider for DartStream.
version: 0.0.1
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  ds_feature_flags_base: ^0.0.1
  ds_standard_features: ^0.1.6
  openfeature_dart_server_sdk: ^0.0.16
  openfeature_provider_intellitoggle: ^0.0.6

dev_dependencies:
  ds_tools_testing: ^0.1.4
