name: ds_intellitoggle_provider
description: IntelliToggle feature flag provider for DartStream.
version: 0.0.2
repository: https://github.com/aortem/dartstream

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  ds_feature_flags_base: ^0.0.1
  ds_standard_features: ^0.1.7
  openfeature_dart_server_sdk: ^0.0.22
  openfeature_provider_intellitoggle: ^0.0.9

dev_dependencies:
  ds_tools_testing: ^0.1.4
