#This pubspec file imports is used for any dependencies for standard Dartstream features.

name: ds_dartweb_framework_base
description: Packages for our dartweb framework - maintained by the Aortem and Dart team.
version: 0.0.1-pre+1
repository: https://github.com/aortem/dartstream

environment:
<<<<<<< HEAD:dartstream/dartstream_backend/packages/frameworks/dart_web/pubspec.yaml
 sdk: ^3.8.1
=======
 sdk: ^3.8.1
>>>>>>> main:dartstream/dartstream_backend/packages/frameworks/dartweb/pubspec.yaml

# Dependencies are added in sections alphabetically and according to features.
dependencies:

# STANDARD PACKAGES - Built By The Dart Team
  ds_standard_features: ^0.0.1-pre+11