#This pubspec file imports is used for any dependencies for standard Dartstream features.
#This works for both mobile and web.
name: ds_dartstream_standard
description: Packages for our standard features - maintained by the Dart team.
version: 0.0.1
repository: https://github.com/aortem/dartstream
publish_to: none

environment:
 sdk: ^3.7.2

# Dependencies are added in sections alphabetically and according to features.
dependencies:

# STANDARD PACKAGES - Built By The Dart Team
  ds_standard_features: ^0.0.2
