name: ds_lifecycle_provider
description: Lifecycle provider implementations for DartStream reactive dataflow.
version: "0.0.1-pre"
repository: https://github.com/aortem/dartstream

publish_to: none # Mark the package as non-publishable for local testing:

environment:
  sdk: ^3.11.0

resolution: workspace

entry_point: "lib/amazon_auth_provider.dart"
