name: ds_cli_util
description: This package has been deprecated. Please use the new CLI tools provided in the `bin` folder of the DartStream framework.
version: 0.0.1-pre+3deprecated
repository: https://github.com/aortem/dartstream

environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  args: ^2.6.0
  ds_tools_testing: ^0.0.1-pre+2
