stages:
  - setup
  - unit_tests
  - integration_tests
  - e2e_tests

# Setup Stage
setup:
  stage: setup
  image: dart:stable
 # tags:
 #   - dart
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
  script:
    - echo "Setting up environment..."
    - cd firebase-dart-admin-auth-sdk
    - dart pub get
  artifacts:
    paths:
      - .dart_tool/
    expire_in: 1h
  retry: 2

# Unit Tests
unit_tests:
  stage: unit_tests
  image: dart:stable
 # tags:
 #   - dart
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
  script:
    - echo "Running Unit Tests..."
    - cd firebase-dart-admin-auth-sdk/firebase-dart-admin-auth-sdk/test/test/unit # Navigate to the directory with pubspec.yaml
    - dart pub get
    - dart test test/unit/ --reporter expanded
  artifacts:
    paths:
      - test-reports/unit/
    expire_in: 1d
  retry: 2

# Integration Tests
integration_tests:
  stage: integration_tests
  image: dart:stable
#  tags:
#    - dart
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
  script:
    - echo "Running Integration Tests..."
    - dart test test/integration/ --reporter expanded
  artifacts:
    paths:
      - test-reports/integration/
    expire_in: 1d
  retry: 2

# End-to-End Tests
e2e_tests:
  stage: e2e_tests
  image: dart:stable
#  tags:
#    - dart
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
  script:
    - echo "Running E2E Tests..."
    - dart test test/e2e/ --reporter expanded
  artifacts:
    paths:
      - test-reports/e2e/
    expire_in: 1d
  retry: 2
