stages:
  - unit_tests

# Unit Tests
unit_tests:
  stage: unit_tests
  image: dart:stable
 # tags:
 #   - dart
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
  script:
    - echo "Running Unit Tests..."
    - cd 
    - dart pub get
    - dart test test/unit/ --reporter expanded
  artifacts:
    paths:
      - test-reports/unit/
    expire_in: 1d
  retry: 2