# This yaml file is a backend integration test for the following items below.
# Tt does not include frontend frameworks.

# Databases (e.g., Firebase, PostgreSQL).
# APIs (e.g., REST or GraphQL endpoints).
# Third-party services (e.g., payment gateways, authentication systems).

stages:
  - setup
  - unit_tests
  - integration_tests
  - e2e_tests

# Setup Stage
setup:
  stage: setup
  image: dart:stable
 # tags:
 #   - dart
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
  script:
    - echo "Setting up environment..."
    - cd dartstream/dartstream_backend
    - dart pub get
  artifacts:
    paths:
      - .dart_tool/
    expire_in: 1h
  retry: 2

# Unit Tests
unit_tests:
  stage: unit_tests
  image: dart:stable
 # tags:
 #   - dart
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
  script:
    - echo "Running Unit Tests..."
    - cd dartstream/dartstream_backend/dartstream/dartstream_backend/test/test/unit # Navigate to the directory with pubspec.yaml
    - dart pub get
    - dart test test/unit/ --reporter expanded
  artifacts:
    paths:
      - test-reports/unit/
    expire_in: 1d
  retry: 2

# Integration Tests
integration_tests:
  stage: integration_tests
  image: dart:stable
#  tags:
#    - dart
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
  script:
    - echo "Running Integration Tests..."
    - dart test test/integration/ --reporter expanded
  artifacts:
    paths:
      - test-reports/integration/
    expire_in: 1d
  retry: 2
