name: "test_project"
version: "stable"
framework: "flutter_web"
engine: "standard"
created: "2025-08-11T21:12:26.945659"
vendor: "gcp"
auth: "firebase"
database: "firebase"
cicd: "gitlab"
configured: "2025-08-11T21:13:14.525309"
