name: google_auth_provider
description: Google authentication provider for Dartstream.
version: 0.0.1-pre+10
repository: https://github.com/dartstream

environment:
 sdk: ">=3.5.2 <4.0.0"

# Dependencies are added in sections alphabetically and according to features. 
dependencies:
  firebase_dart_admin_auth_sdk: ^0.0.1-pre+10 # Include the Firebase Auth SDK
